export const white = '#FFFFFF'
export const black = '#21231D'
export const gray = '#C7D4CA'
export const lightGray = '#efefef'
export const yellow = '#B39C4D'
export const green = '#85B374'
export const rose = '#993412'
