export default {
  title: 'Mi experiencia',
  subtitle: 'Desde que empezé a trabajar en el mundo de la hosteleria, lo he hecho en <span>grandes hoteles y restaurantes</span> tanto en <span>España como en Rusia</span>, y puedo decir que es una de mis pasiones en la vida.',
  jobs: [
    {
      title: 'La terraza del casino (Casino Madrid)',
      subtitle: 'Ayudante',
      text: 'La Terraza del Casino, es uno de los mayores exponentes de la vanguardia gastronómica española. Una propuesta culinaria en la que se busca la originalidad, la creatividad más extrema, la transgresión y la sorpresa en un entorno, sin embargo, tremendamente clásico.',
      time: 'Actualidad',
      class: 'image-right',
      id: '0',
      image: './plato1.jpeg',
      link: '/events',
    },
    {
      title: 'Compañia globus',
      subtitle: 'Chef ejecutivo',
      text: '(2 restaurantes, sala de banquetes y catering)Calle Varobskaia 135,  Kirov, Kirov Oblast, 610000 Rusia. Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)',
      time: '2016 - 2017',
      class: 'image-left',
      id:'1',
      image: './plato2.jpeg',
      link: '/events',
    },
    {
      title: 'Compañia SPk-Neon',
      subtitle: 'Chef ejecutivo',
      text: '(5 locales)Calle Lenina, 73, Kirov, Kirov Oblast, 610000 Rusia. Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)',
      time: '2015 - 2016',
      class: 'image-right',
      id:'2',
      image: './plato3.jpeg',
      link: '/events',
    },
    {
      title: 'Hotel Hilton kirov, Restaurante Karin.',
      subtitle: 'Su chef',
      text: 'Oktyabrsky Prospect 145,610017 Rusia. Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)',
      time: '2014 - 2015',
      class: 'image-left',
      id:'3',
      image: './plato4.jpeg',
      link: '/events',
    },
    {
      title: 'Restaurante колессо (koleso)',
      subtitle: 'Jefe de partida caliente',
      text: 'Calle Spasskaya, 18, Kirov, Kirov Oblast, 610000 Rusia Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)',
      time: '2013 - 2014',
      class: 'image-right',
      id:'4',
      image: './plato5.jpeg',
      link: '/events',
    },
    {
      title: 'Hotel Avant Torrejón ****',
      subtitle: 'Metre de hotel',
      text: 'Avant aeropuerto****Avenida de las estaciones s/n, Torrejón de Ardoz. Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno.',
      time: '2009 - 2013',
      class: 'image-left',
      id:'5',
      image: './plato3.jpeg',
      link: '/events',
    },
    // {
    //   title: 'Restaurante Sula',
    //   subtitle: 'Jefe de Rango',
    //   text: 'Calle Jorge Juan 33, 28001, Madrid. Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)',
    //   time: '2008 - 2009',
    //   class: 'image-right',
    //   id:'6',
    //   image: './plato3.jpeg',
    // },
    // {
    //   title: 'Hotel Asset Torrejon ****',
    //   subtitle: 'Jefe de Rango',
    //   text: 'Avant aeropuerto****Avenida de las estaciones s/n, Torrejón de Ardoz. Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500.',
    //   time: '2007 - 2008',
    //   class: 'image-left',
    //   id:'7',
    //   image: './plato3.jpeg',
    // },
    // {
    //   title: 'Hotel Plaza Castilla *****',
    //   subtitle: 'Practicas relativas al curso de Restauración',
    //   text: 'C/Capitán Haya 43, Madrid España 28020.Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta)',
    //   time: '2006 - 2007',
    //   class: 'image-right',
    //   id:'8',
    //   image: './plato3.jpeg',
    // },
    // {
    //   title: 'Restaurante In-Zalakain',
    //   text: 'C/ Alvarez de Baena, 4, 28006 Madrid, España. Eventualmente ocasiones importantes 2006-2013.Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) ',
    //   time: '2006 - 2013',
    //   class: 'image-left',
    //   id:'9',
    //   image: './plato3.jpeg',
    // }
  ],
}
